// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
public class Test1 {
    private WebDriver driver;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","src/main/resources/chromedriver.exe");
        driver = new ChromeDriver();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void checklogout() {
        driver.get("https://www.saucedemo.com/");
        driver.manage().window().setSize(new Dimension(685, 728));
        driver.findElement(By.id("user-name")).sendKeys("standard_user");
        driver.findElement(By.id("password")).sendKeys("secret_sauce");
        driver.findElement(By.id("login-button")).click();
        driver.findElement(By.id("react-burger-menu-btn")).click();
        assertEquals(driver.findElement(By.id("logout_sidebar_link")).findElement(By.xpath("//a[contains(text(),'Logout')]")).getText(),"LOGOUT");
        driver.findElement(By.id("logout_sidebar_link")).click();
        driver.close();
    }

    @Test
    public void checktext() {
        driver.get("https://www.saucedemo.com/");
        driver.manage().window().setSize(new Dimension(685, 728));
        driver.findElement(By.id("user-name")).sendKeys("standard_user");
        driver.findElement(By.id("password")).sendKeys("secret_sauce");
        driver.findElement(By.id("login-button")).click();
        driver.findElement(By.id("add-to-cart-sauce-labs-backpack")).click();
        driver.findElement(By.id("add-to-cart-sauce-labs-bike-light")).click();
        driver.findElement(By.id("add-to-cart-sauce-labs-bolt-t-shirt")).click();
        driver.findElement(By.id("add-to-cart-sauce-labs-fleece-jacket")).click();
        driver.findElement(By.id("add-to-cart-sauce-labs-onesie")).click();
        driver.findElement(By.id("add-to-cart-test.allthethings()-t-shirt-(red)")).click();
        driver.findElement(By.cssSelector(".shopping_cart_link")).click();
        driver.findElement(By.id("continue-shopping")).click();
        driver.findElement(By.cssSelector(".shopping_cart_badge")).click();
        driver.findElement(By.id("checkout")).click();
        driver.findElement(By.id("first-name")).sendKeys("Alex");
        driver.findElement(By.id("last-name")).sendKeys("Pavliuk");
        driver.findElement(By.id("postal-code")).sendKeys("2548");
        driver.findElement(By.id("continue")).click();
        driver.findElement(By.id("finish")).click();
        assertEquals(driver.findElement(By.className("checkout_complete_container")).findElement(By.className("complete-header")).getText(),"THANK YOU FOR YOUR ORDER");
        assertEquals(driver.findElement(By.className("checkout_complete_container")).findElement(By.className("complete-text")).getText(),"Your order has been dispatched, and will arrive just as fast as the pony can get there!");
        assertEquals(driver.findElement(By.className("header_secondary_container")).findElement(By.className("title")).getText(),"CHECKOUT: COMPLETE!");
        driver.close();
    }
}

